// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoSite: typeof import('./components/DemoSite.vue')['default']
    DemoSites: typeof import('./components/DemoSites.vue')['default']
    DisplayIcon: typeof import('./components/DisplayIcon.vue')['default']
  }
}
